import type { Storyline, StoryEvent, EventConnection, Character, EventType, Script, ScriptData } from './types';

// More detailed initial data for a richer user experience.

const initialScriptData: ScriptData = {
  storylines: [
    { id: 'sl1', name: '谋杀案调查', description: '赫尔克里·波洛对东方快车上发生的谋杀案的调查过程。', color: '#3b82f6' },
    { id: 'sl2', name: '阿姆斯特朗案件背景', description: '与所有乘客都有关的过去悲剧，是谋杀的动机。', color: '#f97316' },
  ],
  eventTypes: [
    { id: 'et1', name: '关键情节', color: '#ef4444' },
    { id: 'et2', name: '线索发现', color: '#eab308' },
    { id: 'et3', name: '审讯/证词', color: '#8b5cf6' },
    { id: 'et4', name: '背景故事', color: '#10b981'},
  ],
  characters: [
    { id: 'c1', name: '赫尔克里·波洛', description: '世界著名的比利时侦探，以其敏锐的观察力和心理分析能力而闻名。' },
    { id: 'c2', name: '塞缪尔·雷切特', description: '被害人，一个看似富有的美国商人，真实身份是绑架并杀害黛西·阿姆斯特朗的凶手卡塞蒂。' },
    { id: 'c3', name: '布克先生', description: '国际卧铺车公司的董事，波洛的老朋友，邀请波洛协助调查。' },
    { id: 'c4', name: '康斯坦丁医生', description: '希腊医生，与波洛和布克先生一同检查尸体，提供了医学上的专业意见。' },
    { id: 'c5', name: '赫克托·麦奎因', description: '雷切特的秘书，其父亲是处理阿姆斯特朗案件的地方检察官，因父亲被卡塞蒂毁掉名誉而怀恨在心。' },
    { id: 'c6', name: '爱德华·马斯特曼', description: '雷切特的贴身男仆，曾是阿姆斯特朗上校的勤务兵，在战争中受伤。' },
    { id: 'c7', name: '哈巴德夫人', description: '吵闹的美国寡妇，真实身份是著名演员琳达·雅顿，黛西的外祖母，复仇计划的主谋。' },
    { id: 'c8', name: '格丽塔·奥尔森', description: '瑞典传教士，曾是黛西·阿姆斯特朗的护士，因自己的失误导致黛西被绑架而深感自责。' },
    { id: 'c9', name: '德拉戈米罗夫公主', description: '年迈的俄国贵族，索尼娅·阿姆斯特朗（黛西的母亲）的教母，非常珍视阿姆斯特朗家族。' },
    { id: 'c10', name: '希尔德加德·施密特', description: '德拉戈米罗夫公主的贴身女仆，曾是阿姆斯特朗家的厨师。' },
    { id: 'c11', name: '安德雷尼伯爵', description: '匈牙利外交官，深爱妻子，为了保护她而替她行凶。' },
    { id: 'c12', name: '安德雷尼伯爵夫人', description: '伯爵的年轻妻子，真实身份是海伦娜·戈登堡，索尼娅·阿姆斯特朗的妹妹，黛西的姨妈。' },
    { id: 'c13', name: '阿巴思诺上校', description: '从印度归来的英国军官，曾是阿姆斯特朗上校的朋友和战友。' },
    { id: 'c14', name: '玛丽·德贝纳姆', description: '家庭女教师，曾是阿姆斯特朗家的家庭教师，性格冷静沉着。' },
    { id: 'c15', name: '安东尼奥·福斯卡雷利', description: '意大利裔美国汽车推销员，曾是阿姆斯特朗家的司机，深爱着小黛西。' },
    { id: 'c16', name: '赛勒斯·哈德曼', description: '伪装成打字机推销员的美国私家侦探，曾爱慕阿姆斯特朗家那位因被诬陷而自杀的女仆。' },
    { id: 'c17', name: '皮埃尔·米歇尔', description: '列车长，阿姆斯特朗家自杀女仆的父亲。' },
  ],
  events: [
    { id: 'e1', title: '波洛登上东方快车', date: '1934-01-13 08:00:00', storylineId: 'sl1', typeId: 'et1', description: '因紧急公务，赫尔克里·波洛在伊斯坦布尔意外地登上了满员的东方快车，由老友布克先生为他安排了铺位。', charactersInvolved: ['c1', 'c3'] },
    { id: 'e2', title: '雷切特请求保护', date: '1934-01-13 13:00:00', storylineId: 'sl1', typeId: 'et1', description: '在餐车上，雷切特告诉波洛自己收到了死亡威胁信，并试图以高价雇佣他作为保镖，但波洛因厌恶其人而断然拒绝。', charactersInvolved: ['c1', 'c2'] },
    { id: 'e3', title: '列车被困于大雪', date: '1934-01-14 00:30:00', storylineId: 'sl1', typeId: 'et1', description: '午夜过后，东方快车在南斯拉夫境内遭遇暴风雪，被迫停在一处偏僻的铁轨上，与外界隔绝。', charactersInvolved: ['c1', 'c3', 'c17'] },
    { id: 'e4', title: '发现谋杀案', date: '1934-01-14 09:00:00', storylineId: 'sl1', typeId: 'et1', description: '清晨，雷切特被发现死在自己从内部反锁的包厢里，身中十二刀，伤口深浅不一。', charactersInvolved: ['c1', 'c2', 'c3', 'c4', 'c17'] },
    { id: 'e5', title: '初步调查与现场疑点', date: '1934-01-14 09:30:00', storylineId: 'sl1', typeId: 'et3', description: '波洛、布克先生和康斯坦丁医生开始调查。现场有多处矛盾的线索：一扇开着的窗户、不同力度的刀伤、一只停在凌晨1:15的怀表。', charactersInvolved: ['c1', 'c3', 'c4'] },
    { id: 'e6', title: '烧焦的信件揭示身份', date: '1934-01-14 10:00:00', storylineId: 'sl2', typeId: 'et2', description: '波洛巧妙地还原了一封烧毁的信件碎片，揭示了雷切特的真实身份——几年前震惊美国的阿姆斯特朗女童绑架撕票案的主犯卡塞蒂。', charactersInvolved: ['c1', 'c2'] },
    { id: 'e7', title: '开始审问乘客', date: '1934-01-14 10:30:00', storylineId: 'sl1', typeId: 'et3', description: '波洛在餐车设立了临时法庭，逐一审问所有乘客和乘务员，每个人似乎都有不在场证明，但他们的证词中又充满了破绽。', charactersInvolved: ['c1', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12', 'c13', 'c14', 'c15', 'c16', 'c17'] },
    { id: 'e8', title: '发现矛盾的线索', date: '1934-01-14 14:00:00', storylineId: 'sl1', typeId: 'et2', description: '调查过程中，各种看似指向不同凶手的线索接连出现：一块带有字母“H”的女士手帕、一根烟斗通条、一件藏在波洛行李箱里的红色和服，以及一套列车员制服。', charactersInvolved: ['c1', 'c7', 'c9', 'c13'] },
    { id: 'e9', title: '哈巴德夫人的匕首', date: '1934-01-14 15:00:00', storylineId: 'sl1', typeId: 'et3', description: '哈巴德夫人声称凶手曾穿过她的包厢，后来在她的海绵袋里发现了凶器——一把匕首，这加深了案件的戏剧性。', charactersInvolved: ['c1', 'c7'] },
    { id: 'e12', title: '揭示所有人的关联', date: '1934-01-15 10:00:00', storylineId: 'sl2', typeId: 'et4', description: '波洛通过分析证词和每个人的背景，最终发现了一个惊人的事实：车上除了他自己、布克和医生，其他所有乘客都与阿姆斯特朗惨案有直接或间接的联系。', charactersInvolved: ['c1', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12', 'c13', 'c14', 'c15', 'c16', 'c17'] },
    { id: 'e13', title: '第一种解答：外部凶手', date: '1934-01-15 11:00:00', storylineId: 'sl1', typeId: 'et1', description: '波洛向众人提出了第一种理论：一个黑手党仇家化装成列车员，在列车停下前行凶并从温科夫齐车站逃走。这个解答可以解释部分线索，但存在许多疑点。', charactersInvolved: ['c1', 'c3', 'c4'] },
    { id: 'e14', title: '第二种解答：集体复仇', date: '1934-01-15 11:15:00', storylineId: 'sl1', typeId: 'et1', description: '波洛提出了第二种更惊人的理论：所有12名与阿姆斯特朗案相关的乘客组成了一个复仇陪审团，共同策划并执行了对卡塞蒂的处决，每人一刀，象征着法律的审判。', charactersInvolved: ['c1', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12', 'c13', 'c14', 'c15', 'c16', 'c17'] },
    { id: 'e15', title: '真相大白与主谋承认', date: '1934-01-15 11:30:00', storylineId: 'sl1', typeId: 'et1', description: '在波洛的推理下，哈巴德夫人（琳达·雅顿）承认了是她策划了这场复仇。所有人都参与了行动，共同伸张了法律无法给予的正义。', charactersInvolved: ['c1', 'c7'] },
    { id: 'e16', title: '正义的选择', date: '1934-01-15 12:00:00', storylineId: 'sl1', typeId: 'et1', description: '面对两种解答，波洛选择了人性。他决定向南斯拉夫警方提交第一种简单的解答，让复仇者们逃脱法律的制裁，因为他认为更高层次的正义已得到伸张。', charactersInvolved: ['c1', 'c3', 'c4'] },
  ],
  eventConnections: [
    { id: 'conn1', fromEventId: 'e2', toEventId: 'e4', description: '拒绝请求后' },
    { id: 'conn2', fromEventId: 'e3', toEventId: 'e4', description: '为谋杀创造了封闭环境' },
    { id: 'conn3', fromEventId: 'e4', toEventId: 'e5', description: '导致调查开始' },
    { id: 'conn4', fromEventId: 'e5', toEventId: 'e6', description: '在调查中发现' },
    { id: 'conn5', fromEventId: 'e6', toEventId: 'e12', description: '揭示了所有人的共同动机' },
    { id: 'conn6', fromEventId: 'e12', toEventId: 'e14', description: '形成了集体复仇理论' },
    { id: 'conn7', fromEventId: 'e14', toEventId: 'e15', description: '被主谋证实' },
    { id: 'conn8', fromEventId: 'e15', toEventId: 'e16', description: '促使波洛做出最终决定' },
    { id: 'conn9', fromEventId: 'e4', toEventId: 'e7', description: '需要审问所有嫌疑人' },
    { id: 'conn10', fromEventId: 'e7', toEventId: 'e8', description: '审问中发现更多矛盾' },
  ],
  characterRelationships: [
    { id: 'cr1', fromCharacterId: 'c1', toCharacterId: 'c3', relationshipType: '朋友', direction: 'bidirectional' },
    { id: 'cr2', fromCharacterId: 'c7', toCharacterId: 'c2', relationshipType: '不共戴天的仇人', direction: 'forward' },
    { id: 'cr3', fromCharacterId: 'c7', toCharacterId: 'c12', relationshipType: '母女', direction: 'bidirectional' },
    { id: 'cr4', fromCharacterId: 'c9', toCharacterId: 'c12', relationshipType: '教母/教女', direction: 'forward' },
    { id: 'cr5', fromCharacterId: 'c13', toCharacterId: 'c14', relationshipType: '恋人', direction: 'bidirectional' },
    { id: 'cr6', fromCharacterId: 'c11', toCharacterId: 'c12', relationshipType: '夫妻', direction: 'bidirectional' },
    { id: 'cr7', fromCharacterId: 'c5', toCharacterId: 'c2', relationshipType: '雇主（憎恨）', direction: 'forward' },
    { id: 'cr8', fromCharacterId: 'c6', toCharacterId: 'c2', relationshipType: '雇主（憎恨）', direction: 'forward' },
  ],
  characterGroups: [
    {
      id: 'cg-revenge',
      name: '复仇同盟',
      description: '所有参与刺杀雷切特（卡塞蒂）的乘客，他们都与阿姆斯特朗案有直接或间接的联系，共同组成了一个执行正义的“陪审团”。',
      color: '#a855f7',
      characterIds: ['c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12', 'c13', 'c14', 'c15', 'c16', 'c17']
    },
    {
      id: 'cg-investigators',
      name: '调查小组',
      description: '负责调查谋杀案的三人组。',
      color: '#22d3ee',
      characterIds: ['c1', 'c3', 'c4']
    }
  ],
  eraOrder: ['公元前', '公元纪年'],
};

const solitudeScriptData: ScriptData = {
  storylines: [
    { id: 'sl_sol_1', name: '布恩迪亚家族的命运', description: '一个家族七代人无法摆脱的循环宿命，以及他们与孤独的斗争。', color: '#10b981' },
    { id: 'sl_sol_2', name: '马孔多的魔幻与现实', description: '发生在马孔多镇的奇幻、荒诞与不可思议的事件，以及它从建立到毁灭的历程。', color: '#8b5cf6' },
    { id: 'sl_sol_3', name: '历史与遗忘', description: '内战、香蕉公司、大屠杀等真实历史事件如何在马孔多被扭曲和遗忘。', color: '#f97316' },
  ],
  eventTypes: initialScriptData.eventTypes,
  characters: [
    { id: 'c_sol_1', name: '何塞·阿尔卡蒂奥·布恩迪亚', description: '家族创始人，充满狂热的想象力和求知欲，最终被绑在栗子树上度过余生。' },
    { id: 'c_sol_2', name: '乌尔苏拉·伊瓜兰', description: '家族的女族长，坚韧不拔，是家族的实际支柱，活了一个多世纪，见证了家族的兴衰。' },
    { id: 'c_sol_3', name: '奥雷里亚诺·布恩迪亚上校', description: '家族第二代，发动了32场内战，一生都在与孤独搏斗，晚年在作坊里制作小金鱼。' },
    { id: 'c_sol_4', name: '何塞·阿尔卡蒂奥（第二代）', description: '上校的哥哥，体格健壮，充满原始的生命力，最终离奇死亡。' },
    { id: 'c_sol_5', name: '阿玛兰妲', description: '家族的女儿，一生都在与孤独和死亡编织的宿命中挣扎，为自己编织寿衣。' },
    { id: 'c_sol_6', name: '梅尔基亚德斯', description: '吉卜赛人，带来科学与魔法，并用梵文写下家族百年命运的羊皮卷。' },
    { id: 'c_sol_7', name: '俏姑娘雷麦黛丝', description: '美得令人窒息，纯洁得不食人间烟火，最终在一个下午随床单升天。' },
    { id: 'c_sol_8', name: '奥雷里亚诺第二', description: '热爱狂欢与挥霍，与佩特拉·科特斯的情爱让牲畜疯狂繁殖。' },
    { id: 'c_sol_9', name: '何塞·阿尔卡蒂奥第二', description: '奥雷里亚诺第二的孪生兄弟，香蕉公司大屠杀的唯一幸存者和见证人。' },
    { id: 'c_sol_10', name: '费尔南达·德尔·卡皮奥', description: '来自高原的没落贵族，奥雷里亚诺第二的妻子，刻板而严厉，给家族带来了陈腐的规矩。' },
    { id: 'c_sol_11', name: '梅梅', description: '奥雷里亚诺第二与费尔南达的女儿，因与马乌里西奥·巴比伦的禁忌之爱被送往修道院。' },
    { id: 'c_sol_12', name: '奥雷里亚诺·巴比伦', description: '梅梅的私生子，家族的最后一代，在孤独中成长，最终破译了羊皮卷。' },
    { id: 'c_sol_13', name: '阿玛兰妲·乌尔苏拉', description: '家族最后一位女性，从欧洲归来，试图重振家族，与外甥奥雷里亚诺·巴比伦相爱。' },
  ],
  events: [
    { id: 'e_sol_1', title: '马孔多的建立', date: '第一代 1.0101', storylineId: 'sl_sol_2', typeId: 'et1', description: '何塞·阿尔卡蒂奥·布恩迪亚因杀死普鲁邓希奥·阿基拉尔而受到其鬼魂的困扰，被迫带领家族迁徙，最终在一片河床上建立了马孔多。', charactersInvolved: ['c_sol_1', 'c_sol_2'] },
    { id: 'e_sol_2', title: '发现冰块', date: '第一代 5.0101', storylineId: 'sl_sol_2', typeId: 'et2', description: '梅尔基亚德斯的吉卜赛人带来了各种新奇事物，何塞·阿尔卡蒂奥·布恩迪亚触摸冰块时，将其视为他那个时代最伟大的发明。', charactersInvolved: ['c_sol_1', 'c_sol_6'] },
    { id: 'e_sol_3', title: '失眠症瘟疫', date: '第一代 10.0101', storylineId: 'sl_sol_2', typeId: 'et4', description: '一场瘟疫让整个马孔多的人都失去了记忆和睡眠，人们不得不在物品上贴标签以记住它们的用途，直到梅尔基亚德斯带来解药。', charactersInvolved: ['c_sol_1', 'c_sol_2', 'c_sol_3', 'c_sol_4', 'c_sol_6'] },
    { id: 'e_sol_4', title: '上校的32场战争', date: '第二代 1.0101', storylineId: 'sl_sol_1', typeId: 'et1', description: '奥雷里亚诺·布恩迪亚上校成为自由派的领袖，发动了32场战争，屡战屡败，最终签订了停战协定，陷入了更深的孤独。', charactersInvolved: ['c_sol_3'] },
    { id: 'e_sol_11', title: '制作与融化小金鱼', date: '第二代 20.0101', storylineId: 'sl_sol_1', typeId: 'et4', description: '战争结束后，上校把自己关在作坊里，日复一日地制作小金鱼，再把它们融化掉，以此来度量自己的孤独。', charactersInvolved: ['c_sol_3'] },
    { id: 'e_sol_5', title: '俏姑娘升天', date: '第四代 1.0101', storylineId: 'sl_sol_2', typeId: 'et1', description: '俏姑娘雷麦黛丝在晾晒白色床单时，连同床单一起，在一阵风中升入了天空，永远消失。', charactersInvolved: ['c_sol_7', 'c_sol_10'] },
    { id: 'e_sol_6', title: '香蕉公司到来', date: '第四代 5.0101', storylineId: 'sl_sol_3', typeId: 'et1', description: '一家美国香蕉公司来到马孔多，带来了现代化的铁路和虚假的繁荣，也带来了剥削和冲突，永远地改变了小镇。', charactersInvolved: ['c_sol_8', 'c_sol_9'] },
    { id: 'e_sol_7', title: '香蕉公司大屠杀', date: '第四代 8.0101', storylineId: 'sl_sol_3', typeId: 'et1', description: '香蕉公司工人罢工，政府军队在广场上屠杀了三千多名工人，并用火车运走尸体扔进大海。何塞·阿尔卡蒂奥第二是唯一的幸存者。', charactersInvolved: ['c_sol_9'] },
    { id: 'e_sol_12', title: '官方的遗忘', date: '第四代 8.0102', storylineId: 'sl_sol_3', typeId: 'et4', description: '大屠杀之后，官方否认了事件的发生，马孔多的居民也陷入了集体失忆，只有何塞·阿尔卡蒂奥第二记得真相。', charactersInvolved: ['c_sol_9'] },
    { id: 'e_sol_8', title: '持续五年的大雨', date: '第五代 1.0101', storylineId: 'sl_sol_2', typeId: 'et4', description: '大屠杀之后，马孔多下了一场持续四年十一月零两天的大雨，几乎摧毁了一切，也洗刷了历史的痕迹。', charactersInvolved: ['c_sol_8', 'c_sol_10'] },
    { id: 'e_sol_9', title: '破译羊皮卷', date: '第六代 20.0101', storylineId: 'sl_sol_1', typeId: 'et2', description: '家族的最后一个奥雷里亚诺，在与姑妈阿玛兰妲·乌尔苏拉的爱情中，终于破译了梅尔基亚德斯留下的羊皮卷，理解了家族的百年宿命。', charactersInvolved: ['c_sol_12', 'c_sol_13', 'c_sol_6'] },
    { id: 'e_sol_10', title: '家族的终结', date: '第六代 20.0102', storylineId: 'sl_sol_1', typeId: 'et1', description: '羊皮卷预言：“家族的第一个人被绑在树上，最后一个人正在被蚂蚁吃掉。”当奥雷里亚诺破译完最后一页时，一场飓风将马孔多和整个布恩迪亚家族从地图上抹去。', charactersInvolved: ['c_sol_12'] },
  ],
  eventConnections: [
    { id: 'conn_sol_1', fromEventId: 'e_sol_1', toEventId: 'e_sol_2', description: '为...奠定了基础' },
    { id: 'conn_sol_2', fromEventId: 'e_sol_6', toEventId: 'e_sol_7', description: '矛盾激化导致' },
    { id: 'conn_sol_3', fromEventId: 'e_sol_7', toEventId: 'e_sol_12', description: '是官方试图掩盖的真相' },
    { id: 'conn_sol_4', fromEventId: 'e_sol_12', toEventId: 'e_sol_8', description: '是...的后果' },
    { id: 'conn_sol_5', fromEventId: 'e_sol_2', toEventId: 'e_sol_9', description: '留下了预言' },
    { id: 'conn_sol_6', fromEventId: 'e_sol_9', toEventId: 'e_sol_10', description: '揭示了家族的最终结局' },
  ],
  characterRelationships: [
    { id: 'cr_sol_1', fromCharacterId: 'c_sol_1', toCharacterId: 'c_sol_2', relationshipType: '夫妻/表亲', direction: 'bidirectional' },
    { id: 'cr_sol_2', fromCharacterId: 'c_sol_2', toCharacterId: 'c_sol_3', relationshipType: '母子', direction: 'bidirectional' },
    { id: 'cr_sol_3', fromCharacterId: 'c_sol_2', toCharacterId: 'c_sol_4', relationshipType: '母子', direction: 'bidirectional' },
    { id: 'cr_sol_4', fromCharacterId: 'c_sol_2', toCharacterId: 'c_sol_5', relationshipType: '母女', direction: 'bidirectional' },
    { id: 'cr_sol_5', fromCharacterId: 'c_sol_3', toCharacterId: 'c_sol_4', relationshipType: '兄弟', direction: 'bidirectional' },
    { id: 'cr_sol_6', fromCharacterId: 'c_sol_1', toCharacterId: 'c_sol_6', relationshipType: '朋友', direction: 'bidirectional' },
    { id: 'cr_sol_7', fromCharacterId: 'c_sol_8', toCharacterId: 'c_sol_9', relationshipType: '孪生兄弟', direction: 'bidirectional' },
    { id: 'cr_sol_8', fromCharacterId: 'c_sol_8', toCharacterId: 'c_sol_10', relationshipType: '夫妻', direction: 'bidirectional' },
    { id: 'cr_sol_9', fromCharacterId: 'c_sol_10', toCharacterId: 'c_sol_11', relationshipType: '母女', direction: 'bidirectional' },
    { id: 'cr_sol_10', fromCharacterId: 'c_sol_12', toCharacterId: 'c_sol_11', relationshipType: '私生子', direction: 'backward' },
    { id: 'cr_sol_11', fromCharacterId: 'c_sol_12', toCharacterId: 'c_sol_13', relationshipType: '爱人/甥舅', direction: 'bidirectional' },
  ],
  characterGroups: [],
  eraOrder: ['第一代', '第二代', '第三代', '第四代', '第五代', '第六代'],
};

const threeBodyScriptData: ScriptData = {
  storylines: [
    { id: 'sl_3body_1', name: '地球往事', description: '红岸基地、与三体世界的初次接触，以及地球三体组织的崛起。', color: '#3b82f6' },
    { id: 'sl_3body_2', name: '黑暗森林', description: '面壁计划的实施，黑暗森林法则的发现，以及威慑纪元的建立。', color: '#f97316' },
    { id: 'sl_3body_3', name: '死神永生', description: '威慑的终结，宇宙社会学的残酷真相，以及太阳系的二维化。', color: '#8b5cf6' },
  ],
  eventTypes: initialScriptData.eventTypes,
  characters: [
    { id: 'c_3body_0', name: '汪淼', description: '纳米材料学家，第一部的主角，通过《三体》游戏了解三体世界。' },
    { id: 'c_3body_1', name: '叶文洁', description: '天体物理学家，因个人遭遇对人类绝望，第一个与三体世界建立联系的地球人，地球三体组织（ETO）的精神领袖。' },
    { id: 'c_3body_2', name: '罗辑', description: '社会学家，玩世不恭，意外成为第二代面壁者，黑暗森林威慑的建立者和第一任执剑人。' },
    { id: 'c_3body_3', name: '史强', description: '身经百战的刑警，行事粗犷但内心细腻，保护过多位关键人物，是汪淼和罗辑的守护者。' },
    { id: 'c_3body_4', name: '程心', description: '航天工程师，充满圣母般的爱心，提出阶梯计划，成为第二任执剑人，最终见证了宇宙的终结。' },
    { id: 'c_3body_5', name: '云天明', description: '身患绝症的航天工程师，暗恋程心，将自己的大脑通过阶梯计划送往三体舰队，后通过三个童话故事传递关键信息。' },
    { id: 'c_3body_6', name: '章北海', description: '“自然选择”号舰长，坚定的逃亡主义者，是人类舰队中真正的“思想钢印”者。' },
    { id: 'c_3body_7', name: '托马斯·维德', description: '前CIA局长，冷酷果决，为达目的不择手段，推动曲率驱动飞船的研究。' },
    { id: 'c_3body_8', name: '智子', description: '三体世界制造的质子大小的智能机器人，用于锁死地球基础科学、进行实时监视，并作为与人类沟通的使者。' },
    { id: 'c_3body_9', name: '歌者', description: '一个未知的高级文明“清理员”，发现了太阳系坐标后，随手向太阳系投掷了二向箔。' },
  ],
  events: [
    { id: 'e_3body_1', title: '红岸的第一次呼叫', date: '1971-11-01 00:00:00', storylineId: 'sl_3body_1', typeId: 'et4', description: '叶文洁在红岸基地利用太阳作为信号放大器，向宇宙发出了地球文明的第一声呼唤，暴露了地球的坐标。', charactersInvolved: ['c_3body_1'] },
    { id: 'e_3body_2', title: '“不要回答！”', date: '1979-01-01 00:00:00', storylineId: 'sl_3body_1', typeId: 'et2', description: '三体世界的一位和平主义监听员收到了叶文洁的信息，并发出了“不要回答”的警告，但叶文洁因对人性的绝望，选择了再次回应。', charactersInvolved: ['c_3body_1'] },
    { id: 'e_3body_3', title: '智子展开锁死科技', date: '危机纪元 1.0101', storylineId: 'sl_3body_1', typeId: 'et1', description: '三体世界将一个质子进行二维展开，蚀刻成超级计算机后送到地球，即“智子”。它干扰了所有高能物理实验，锁死了人类的基础科学。', charactersInvolved: ['c_3body_8'] },
    { id: 'e_3body_4', title: '古筝行动', date: '危机纪元 3.0101', storylineId: 'sl_3body_1', typeId: 'et1', description: '在巴拿马运河，利用汪淼研制的纳米“飞刃”切割“审判日”号轮船，获取了储存在其中的三体与ETO的全部信息。', charactersInvolved: ['c_3body_3', 'c_3body_0'] },
    { id: 'e_3body_5', title: '面壁计划启动', date: '危机纪元 4.0101', storylineId: 'sl_3body_2', typeId: 'et1', description: '由于智子能监视一切，联合国启动面壁计划，选出四位面壁者利用大脑进行思考制定战略，而ETO则相应派出破壁人。罗辑意外被选中。', charactersInvolved: ['c_3body_2'] },
    { id: 'e_3body_6', title: '罗辑的“咒语”实验', date: '危机纪元 8.0101', storylineId: 'sl_3body_2', typeId: 'et2', description: '罗辑通过叶文洁的提示，领悟了宇宙社会学的黑暗森林法则，并向187J3X1恒星发送了“咒语”（公布其坐标），进行打击实验。', charactersInvolved: ['c_3body_2', 'c_3body_1'] },
    { id: 'e_3body_7', title: '末日战役：“水滴”', date: '危机纪元 205.0101', storylineId: 'sl_3body_2', typeId: 'et1', description: '三体探测器“水滴”以其完美的强相互作用力外壳，在短短几分钟内摧毁了人类集结的2000艘太空战舰的联合舰队。', charactersInvolved: ['c_3body_6', 'c_3body_8'] },
    { id: 'e_3body_8', title: '黑暗森林威慑建立', date: '危机纪元 205.0102', storylineId: 'sl_3body_2', typeId: 'et1', description: '在末日战役后，罗辑通过“雪地工程”验证了咒语的有效性，并威胁向全宇宙广播三体世界的坐标，成功建立了脆弱的战略平衡。', charactersInvolved: ['c_3body_2'] },
    { id: 'e_3body_9', title: '阶梯计划', date: '威慑纪元 5.0101', storylineId: 'sl_3body_3', typeId: 'et1', description: '程心提出阶梯计划，利用核弹爆炸的辐射帆推动飞船，向三体舰队发送一个探测器。最终云天明的大脑被选中并成功发射。', charactersInvolved: ['c_3body_4', 'c_3body_5', 'c_3body_7'] },
    { id: 'e_3body_10', title: '执剑人交接与威慑失败', date: '威慑纪元 62.0101', storylineId: 'sl_3body_3', typeId: 'et1', description: '程心接任执剑人。在她接手后的几分钟内，三体世界立刻发动攻击，摧毁了地球的引力波广播系统，“水滴”封锁了太阳，威慑纪元结束。', charactersInvolved: ['c_3body_4', 'c_3body_2', 'c_3body_8'] },
    { id: 'e_3body_11', title: '三体坐标被广播', date: '威慑纪元 62.0102', storylineId: 'sl_3body_3', typeId: 'et1', description: '在太空中的“万有引力”号和“蓝色空间”号，在威慑失败后，启动了引力波广播，向宇宙公布了三体世界的坐标。', charactersInvolved: [] },
    { id: 'e_3body_12', title: '三体星系被光粒摧毁', date: '广播纪元 7.0101', storylineId: 'sl_3body_3', typeId: 'et2', description: '三体星系被来自未知文明的光粒以光速摧毁，证实了黑暗森林打击的存在和残酷性。', charactersInvolved: [] },
    { id: 'e_3body_13', title: '云天明的童话', date: '广播纪元 7.0201', storylineId: 'sl_3body_3', typeId: 'et2', description: '云天明通过与程心会面，讲述了三个童话故事，巧妙地隐藏并传递了关于曲率驱动、黑域（安全声明）等关键技术信息。', charactersInvolved: ['c_3body_5', 'c_3body_4'] },
    { id: 'e_3body_14', title: '太阳系二维化', date: '广播纪元 286.0101', storylineId: 'sl_3body_3', typeId: 'et1', description: '高级文明“歌者”发现了被广播的太阳系，为“清理”威胁，向太阳系投掷了一张二向箔，导致整个太阳系跌落至二维，所有生命和物质被彻底格式化。', charactersInvolved: ['c_3body_9', 'c_3body_4', 'c_3body_2'] },
    { id: 'e_3body_15', title: '宇宙的终结与回归', date: '宇宙终末 1.0101', storylineId: 'sl_3body_3', typeId: 'et1', description: '程心和关一帆从647号小宇宙回归大宇宙，响应“回归运动”的号召，归还了他们“窃取”的物质和能量，见证了宇宙的最终坍缩和重生。', charactersInvolved: ['c_3body_4'] },
  ],
  eventConnections: [
    { id: 'conn_3body_1', fromEventId: 'e_3body_1', toEventId: 'e_3body_2', description: '收到了回应' },
    { id: 'conn_3body_2', fromEventId: 'e_3body_2', toEventId: 'e_3body_3', description: '导致了入侵和科技封锁' },
    { id: 'conn_3body_3', fromEventId: 'e_3body_3', toEventId: 'e_3body_5', description: '迫使人类制定' },
    { id: 'conn_3body_4', fromEventId: 'e_3body_1', toEventId: 'e_3body_6', description: '谈话中提示了罗辑' },
    { id: 'conn_3body_5', fromEventId: 'e_3body_7', toEventId: 'e_3body_8', description: '为威慑创造了条件' },
    { id: 'conn_3body_6', fromEventId: 'e_3body_8', toEventId: 'e_3body_10', description: '被...终结' },
    { id: 'conn_3body_7', fromEventId: 'e_3body_10', toEventId: 'e_3body_11', description: '迫使人类飞船广播坐标' },
    { id: 'conn_3body_8', fromEventId: 'e_3body_11', toEventId: 'e_3body_12', description: '导致' },
    { id: 'conn_3body_9', fromEventId: 'e_3body_12', toEventId: 'e_3body_14', description: '验证了坐标暴露的危险' },
    { id: 'conn_3body_10', fromEventId: 'e_3body_9', toEventId: 'e_3body_13', description: '使得...得以传递信息' },
  ],
  characterRelationships: [
    { id: 'cr_3body_1', fromCharacterId: 'c_3body_2', toCharacterId: 'c_3body_3', relationshipType: '战友/保护者', direction: 'bidirectional' },
    { id: 'cr_3body_2', fromCharacterId: 'c_3body_0', toCharacterId: 'c_3body_3', relationshipType: '保护者', direction: 'forward' },
    { id: 'cr_3body_3', fromCharacterId: 'c_3body_4', toCharacterId: 'c_3body_5', relationshipType: '同学/暗恋', direction: 'backward' },
    { id: 'cr_3body_4', fromCharacterId: 'c_3body_4', toCharacterId: 'c_3body_7', relationshipType: '合作/对抗', direction: 'bidirectional' },
    { id: 'cr_3body_5', fromCharacterId: 'c_3body_2', toCharacterId: 'c_3body_1', relationshipType: '思想继承', direction: 'forward' },
    { id: 'cr_3body_6', fromCharacterId: 'c_3body_0', toCharacterId: 'c_3body_1', relationshipType: '调查对象', direction: 'forward' },
  ],
  characterGroups: [],
  eraOrder: ['公元前', '公元纪年', '危机纪元', '威慑纪元', '广播纪元', '宇宙终末'],
};


export const initialScripts: Script[] = [
  {
    id: 'script-initial',
    name: '东方快车谋杀案',
    data: initialScriptData,
  },
  {
    id: 'script-solitude',
    name: '百年孤独',
    data: solitudeScriptData,
  },
  {
    id: 'script-threebody',
    name: '三体 (全集)',
    data: threeBodyScriptData,
  }
];
